---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: default
type: Opaque
stringData:
  database-url: postgres://user:password@postgres.example.com:5432/mydb

---
apiVersion: pghero.mithucste30.io/v1alpha1
kind: Database
metadata:
  name: example-database-secret
  namespace: default
spec:
  name: production
  databaseType: postgresql
  enabled: true
  urlFromSecret:
    name: postgres-credentials
    key: database-url
